navigate:
  name: Navigate robot
  description: Control robot manually
  fields:
    direction:
      name: Direction
      description: Joystick navigation
      required: true
      example: "backward"
      selector:
        select:
          mode: dropdown
          options:
            - stop
            - backward
            - forward
            - left
            - right

exit_navigation:
  name: Exit navigation mode
  description: Stop controlling robot manually
